databases:
  - name: portfolio-db
    plan: free

services:
  - type: web
    name: portfolio-web
    runtime: python
    plan: free
    rootDir: portfolio          # because manage.py is in the portfolio/ folder
    buildCommand: "../build.sh"
    startCommand: "gunicorn portfolio.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.11"

  - type: redis
    name: portfolio-redis
    ipAllowList: [] # empty means allow all
